### ISSUE TITLE
Unlink fails on Solaris when run from cron as non root.

### ISSUE THREAD

**Issue by janorn** [github/backup-utils#185] opened 2016-03-23 10:34 UTC
On Solaris the default cron PATH is /usr/bin but unlink is located in /usr/sbin.

A simple fix for this is to add /usr/sbin to the PATH in ghe-backup-config.

**Comment by rubiojr** [comment] 2016-04-21 17:23
@janorn we can easily fix this but, in the meantime, can't you add it to the PATH in the crontab file? That'd be better than tweaking `backup-utils` I think.

**Comment by janorn** [comment] 2016-04-21 20:55
Nope,

In Solaris it can only be changed for all users which is not an acceptable
solution.

     The default PATH for user cron jobs is /usr/bin; while

     root cron jobs default to  /usr/sbin:/usr/bin.  The  default

     PATH can be set in /etc/default/cron (see cron(1M)). The TZ,

     HOME, and SHELL environment variables are set to match those

     that are in effect in the crontab file at the time.


As you can se only TZ,HOME and SHELL can be defined in the crontab file.

Från:  Sergio Rubio <notifications@github.com>
Svara till:  github/backup-utils
<reply+00244f057ebc5124051935303150f36c4aeb72dea8455bac92cf000000011330ce8d9
2a169ce0884d4e1@reply.github.com>
Datum:  torsdag 21 april 2016 19:23
Till:  github/backup-utils <backup-utils@noreply.github.com>
Kopia:  Jan Örnstedt <jan.ornstedt@postkodlotteriet.se>, Mention
<mention@noreply.github.com>
Ämne:  Re: [github/backup-utils] Unlink fails on Solaris when run from cron
as non root. (#185)

@janorn <https://github.com/janorn>  we can easily fix this but, in the
meantime, can't you add it to the PATH in the crontab file? That'd be better
than tweaking backup-utils I think.


You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/github/backup-utils/issues/185#issuecomment-213025857>

**Comment by rubiojr** [comment] 2016-04-22 09:00
Thanks @janorn, not familiar with Solaris cron.

**Comment by lildude** [comment] 2017-03-17 13:00
@janorn If all you need to do is add `/usr/sbin` to the `PATH` in ghe-backup-config you can do so by adding `PATH=/usr/sbin:$PATH` to the end of your `backup.config` file within your backup-utils directory.

**Comment by lildude** [comment] 2017-03-17 13:02
I've just realised this is a duplicate of the older https://github.com/github/backup-utils/issues/123.  I'm going to close this issue in favour of that one.

**Closed by lildude** 2017-03-17 13:02 UTC
Labels: xplatform
