### ISSUE TITLE
Problems with backup

### ISSUE THREAD

**Issue by esebastianpe** [github/backup-utils#537] opened 2020-01-23 12:19 UTC
Hi,
I have found some issues doing a backup of a GitHub appliance 18.7 version. When I run ghe-backup, it appears a message: "One or more storage objects were not found on the source appliance. Please contact GitHub ..."
It happens after the storage step. It seems there are some differences between several routes but I don't Know if that could be a problem.
The backup ends but I am not pretty sure if it contains all the information and in a consistency state. 
Do you know if there is any way to check or repair this error?

**Comment by lildude** [comment] 2020-01-23 13:13
The best thing to do here is contact our Enterprise Support as the message states as we'd need to investigate the cause of those errors and doing so may reveal private information that should not be discussed in a public issue like this one.

Please ensure you're using the latest version of backup-utils - 2.19.1 - and if the problem persists, contact our Enterprise Support team using the "Contact GitHub" link at the bottom of any page on GitHub.com.

**Comment by esebastianpe** [comment] 2020-01-24 11:09
OK. That's right, I'm going to open a support ticket with GitHub. Thanks for all :)

**Comment by cainejette** [comment] 2020-06-23 20:39
Great! I will close this now.

**Closed by cainejette** 2020-06-23 20:39 UTC
