### ISSUE TITLE
Check backup and appliance compatibility before restore

### ISSUE THREAD

**Issue by Ollliver** [github/backup-utils#512] opened 2019-08-28 07:00 UTC
Right now a restore attempt of an incompatible backup version (e.g. ghe 2.17, gbu 2.18, backup of version 2.18) can fail during the restore at some point.
Compatiblity should be checked before anything is restored and the utility should fail.

**Comment by danikka15** [comment] 2019-10-28 02:08
Duplicate of #

**Comment by cainejette** [comment] 2020-06-23 20:40
Can you be more specific where this is failing @Ollliver ?

**Comment by djdefi** [comment] 2021-04-01 17:05
Some information about backwards compatibility (restoring to an older release) has been added here: https://github.com/github/backup-utils/blob/master/docs/requirements.md#github-enterprise-server-version-requirements

If that doesn't address your issue, please let us know!

**Closed by djdefi** 2021-04-01 17:05 UTC
