### ISSUE TITLE
Error when running ghe-backup in docker with alpine

### ISSUE THREAD

**Issue by mariusfilipowski** [github/backup-utils#357] opened 2017-12-12 13:44 UTC
We have encapsuled the tools in a docker image that we use.
With  FROM alpine:3.6 or FROM alpine:3.7 we get the following output when running ghe-backup

```
Starting backup of ghe-instance in snapshot 20171212T134059
Connect ghe-instance:122 OK (v2.11.4)
Backing up GitHub settings ...
Backing up SSH authorized keys ...
Backing up SSH host keys ...
Backing up MySQL database ...
Backing up Redis database ...
Backing up audit log ...
Backing up hookshot logs ...
Backing up Git repositories ...
Backing up GitHub Pages ...
Backing up asset attachments ...
Backing up storage data ...
Backing up hook deliveries ...
Backing up custom Git hooks ...
Backing up Elasticsearch indices ...
Completed backup of ghe-instance:122 in snapshot 20171212T134059 at 13:41:03
Checking for leaked ssh keys ...
BusyBox v1.26.2 (2017-11-23 08:40:54 GMT) multi-call binary.

Usage: basename FILE [SUFFIX]

Strip directory path and .SUFFIX from FILE
```

With the debug switch from bash (-x) we get the error narrowed down:
```
+ set -e
++ mktemp -d
+ TEMPDIR=/tmp/tmp.iDbAbc
+ '[' 2 -gt 0 ']'
+ case "$1" in
+ snapshot=/ghe-backup/data/20171212T131230
+ shift
+ shift
+ '[' 0 -gt 0 ']'
++ ps -o args= 1
++ awk '{print $2}'
+ ppid_script='
-f
-f
-x
-x
-o
{print'
+ '[' -n '
-f
-f
-x
-x
-o
{print' ']'
++ basename -f -f -x -x -o '{print'
BusyBox v1.26.2 (2017-11-23 08:40:54 GMT) multi-call binary.

Usage: basename FILE [SUFFIX]

Strip directory path and .SUFFIX from FILE
+ ppid_name=
```

The parameters passed to basename in `ghe-detect-leaked-ssh-keys` in line 37-39 don't seem to work.

Is there a fix or known workaround for alpine linux?

**Comment by lildude** [comment] 2017-12-12 14:08
Hmmm, looks like `ps -o args= $PPID 2>/dev/null | awk '{print $2}'` within your env is returning `-f -f -x -x -o` for some reason suggesting `$PPID` is not the PID of the `ghe-backup` invocation that should be calling this script.

Further up in the debug output we can see the PPID being queried is `1`:

```
++ ps -o args= 1
```

That PID doesn't seem right to me.

I think this may be due to the way you're calling `bin/ghe-backup`.  You've not provided your backup-utils version, Dockerfile or how you're invoking `ghe-backup` within your container so we're in the dark WRT your usage.

That said, we've recently introduced a [Dockerfile](https://github.com/github/backup-utils/blob/master/Dockerfile) and [documentation](https://github.com/github/backup-utils/blob/master/docs/docker.md) in the master branch that uses a Debian Stretch base. Do you see this issue if you use that or use it as inspiration for your own Docker image and usage?

**Comment by mariusfilipowski** [comment] 2017-12-12 14:56
Thanks for the help.
There's nothing special about the Docker file I've built. It is quite similar to the one you are referring to. Instead it is based on Alpine since this is much smaller and the default for our docker images.

The ghe-tools are based on the stable branch just taken by git clone from this repo.

I simply attache to the docker cintainer with docker run -ti --entrypoint" bash" imagefilename 

Then I change to the folder with the backup tools and run them with `./bin/ghe-backup` interactively.

Is Alpine not supported?

**Comment by lildude** [comment] 2017-12-12 17:13
> Then the bash is the root process with pid 1.

Yeah, that's the problem. The PPID should be that of `ghe-backup` as it is what is running `ghe-detect-leaked-ssh-keys`.

> Is Alpine not supported?

I can't really confirm or deny as it's not formally tested and I've not heard any reports of anyone else using it until today 😁.

It's Linux so provided it has all the commands we need, I don't see why it couldn't be.

Is your command definitely starting a bash shell and not something like ash or dash?  I ask because you're not specifying a full path so could it possibly be silently failing or falling back to another shell that isn't bash which is then having problems with `$PPID`?  I've seen reports of dash reporting the wrong PPID so maybe something similar is happening here.  (I'm throwing ideas out to see what sticks 😄)

I'll have a tinker tomorrow :gb: time to see if I can reproduce and workout what's going on.

**Comment by lildude** [comment] 2017-12-12 18:49
You piqued my interested so I dug into it this evening.

The problem is down to Alpine's `ps` or more specifically BusyBox's `ps`. It's a severely cut down `ps`. 

To illustrate this, I created two very simple scripts to mimic the behaviour of `ghe-detect-leaked-ssh-keys`:

foo.sh:
```
#!/bin/bash
./bar.sh
```

bar.sh:
```
#!/bin/bash
echo "==="
ps -o args= $PPID
echo "==="
```

If we run `./foo.sh` in a Debian-based container, we get:

```
root@34a5456955a0:/backup-utils# ./foo.sh
===
/bin/bash ./foo.sh
===
root@34a5456955a0:/backup-utils#
```

But if we run the same script on an Alpine-based container, we get:

```
bash-4.4# ./foo.sh
===
bash
{foo.sh} /bin/bash ./foo.sh
{bar.sh} /bin/bash ./bar.sh
ps -o args= 8734
===
bash-4.4#
```

That's just the output of `ps` with the header set to an empty string. Busybox `ps` is pretty basic and doesn't offer the functionality we're looking for.

The problem is easily solved by installing `procps`:

```
bash-4.4# ./foo.sh
===
/bin/bash ./foo.sh
===
bash-4.4#
```

... and confirmed with a backup:

```
bash-4.4# bin/ghe-backup
Starting backup of 10.0.1.68 in snapshot 20171212T183713
Connect 10.0.1.68:122 OK (v2.11.6)
Backing up GitHub settings ...
Backing up SSH authorized keys ...
Backing up SSH host keys ...
Backing up MySQL database ...
Backing up Redis database ...
Backing up audit log ...
Backing up hookshot logs ...
Backing up Git repositories ...
Backing up GitHub Pages ...
Backing up asset attachments ...
Backing up storage data ...
Backing up hook deliveries ...
Backing up custom Git hooks ...
Backing up Elasticsearch indices ...
Completed backup of 10.0.1.68:122 in snapshot 20171212T183713 at 18:44:57
Checking for leaked ssh keys ...
* No leaked keys found
bash-4.4# echo $?
0
bash-4.4#
```

So with the addition of `procps` to your Alpine-based container, you should find backup-utils _does_ work.

**Comment by mariusfilipowski** [comment] 2017-12-13 07:46
Wow. Thanks for the detailed Explanation. So we should use the Debian base image as in your dockerfile to be sure that it will be supported, right?

**Comment by lildude** [comment] 2018-01-09 14:23
I think this has been addressed so I'm closing this issue. Please feel free to reopen if you have any further questions.

**Closed by lildude** 2018-01-09 14:23 UTC
